[env:wiscore_rak4631]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<*> -<tx_main.cpp>
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    jgromes/RadioLib @ ^7.1.1

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
build_src_filter = +<*> -<main.cpp>
lib_deps =
    ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.3.0
    bblanchon/ArduinoJson @ ^6.21.3
    jgromes/RadioLib @ ^7.1.1
    h2zero/NimBLE-Arduino @ ^1.4.1

[env:native]
platform = native
test_framework = unity
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
